# Generated by Django 5.0.2 on 2024-03-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_exercisetype_intensity_exercise_workouthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('Cardio', 'Cardio'), ('Strength Training', 'Strength Training'), ('Flexibility', 'Flexibility'), ('Yoga', 'Yoga'), ('Pilates', 'Pilates'), ('HIIT', 'HIIT'), ('CrossFit', 'CrossFit'), ('Swimming', 'Swimming'), ('Cycling', 'Cycling'), ('Running', 'Running'), ('Walking', 'Walking'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='intensity',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='duration',
            field=models.DurationField(choices=[('0:15:00', '15 minutes'), ('0:30:00', '30 minutes'), ('0:45:00', '45 minutes'), ('1:00:00', '1 hour'), ('1:15:00', '1 hour 15 minutes'), ('1:30:00', '1 hour 30 minutes'), ('1:45:00', '1 hour 45 minutes'), ('2:00:00', '2 hours'), ('2:15:00', '2 hours 15 minutes'), ('2:30:00', '2 hours 30 minutes'), ('2:45:00', '2 hours 45 minutes'), ('3:00:00', '3 hours')]),
        ),
        migrations.DeleteModel(
            name='ExerciseType',
        ),
        migrations.DeleteModel(
            name='Intensity',
        ),
    ]
