# Generated by Django 5.0.2 on 2024-03-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_alter_exercise_exercise_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='duration',
            field=models.CharField(choices=[('0:15:00', '15 minutes'), ('0:30:00', '30 minutes'), ('0:45:00', '45 minutes'), ('1:00:00', '1 hour'), ('1:15:00', '1 hour 15 minutes'), ('1:30:00', '1 hour 30 minutes'), ('1:45:00', '1 hour 45 minutes'), ('2:00:00', '2 hours'), ('2:15:00', '2 hours 15 minutes'), ('2:30:00', '2 hours 30 minutes'), ('2:45:00', '2 hours 45 minutes'), ('3:00:00', '3 hours')], max_length=8),
        ),
    ]
