# Generated by Django 5.0.2 on 2024-03-09 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_alter_exercise_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkoutHistory',
        ),
    ]
