# Generated by Django 5.0.2 on 2024-03-09 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0005_delete_workouthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='alone_or_with_friends',
        ),
    ]
